name: Code Check

on:
  pull_request:
    branches:
      - main

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Check Formatting (Spotless)
        run: mvn spotless:check

      - name: Run Linter (Checkstyle)
        run: mvn checkstyle:check

      - name: Run Unit Tests
        run: mvn test
